name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

<<<<<<< HEAD
=======
  workflow_dispatch:

>>>>>>> upstream/main
jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test code and Create Test Coverage Reports
        uses: actions/setup-node@v4
        with:
<<<<<<< HEAD
          node-version: 20
          cache: npm
      - run: |
          npm ci
          npm run build
          npm run format:check
          npm run lint
          npm test

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag cdp-node-backend-template .
          exit $?

#      - name: SonarCloud Scan
#        if: github.actor != 'dependabot[bot]'
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
=======
          node-version: 22
          cache: npm
      - run: |
          npm ci

      - name: Build Docker Image
        run: |
          set +e
          docker build --no-cache --tag fcp-sfd-data .
          exit $?

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml run --rm "fcp-sfd-data"

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
>>>>>>> upstream/main
