name: Publish

on:
  push:
    branches:
      - main
<<<<<<< HEAD
=======
  workflow_dispatch:
>>>>>>> upstream/main

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  AWS_REGION: eu-west-2
  AWS_ACCOUNT_ID: "094954420758"

jobs:
  build:
    if: github.run_number != 1
    name: CDP-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

<<<<<<< HEAD
=======
      - name: Create Test Coverage Reports
        run: |
          npm ci

      - name: Run Tests
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml run --rm "fcp-sfd-data"

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

>>>>>>> upstream/main
      - name: Build and Publish
        uses: DEFRA/cdp-build-action/build@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD

#      - name: Create Test Coverage Reports
#        run: |
#          npm ci
#          npm run build
#          npm test
#
#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
=======
>>>>>>> upstream/main
